version: "3"
services:
  postgres-botner:
    container_name: postgres-botner
    image: postgres:12
    environment:
      POSTGRES_USER: honza-bot
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: HonzaBotner
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
